### ISSUE TITLE
Support search by related fields within an object in an array

### ISSUE THREAD

**Issue by locnguyenx** [moqui/moqui-elasticsearch#9] opened 2017-04-11 16:48 UTC
As I need to search Product DataDocument (using `popc` index) with criteria in which its related entity must have matching of several fields together, for example:
- **price**: `priceTypeEnumId` and `price`
- or **dimension**: `dimensionTypeId` and `dimensionValue`

The search result is not correct with current DataDocument mapping properties because any document may be matched if one child objects meets a condition and the rest may be matched by other child.

Example
**Search by query string**: prices.priceTypeEnumId:PptList AND prices.price:16.99
**Search result**: productId = DEMO_1_1
**Expected result**: not found any document

If I change the mapping of document to use `nested` object at related property, and use nested query then I the result as expected.

However, the problem is that many search functions in mantle or PopCommerce will not work correctly with the new mapping.

Is there a recommended solution for my requirement (don't need to change document mapping)?

**Comment by shendepu** [comment] 2017-04-12 00:58
I think the elasticsearch docs indicates it clearly https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html, the difference between array and nested datatype. 

> Arrays of objects do not work as you would expect: you cannot query each object independently of the other objects in the array. If you need to be able to do this then you should use the nested datatype instead of the object datatype.

So to your requirement, you have to use nested datatype, and then change query in PopCommerce in your fork to work with nested datatype.

**Comment by locnguyenx** [comment] 2017-04-12 02:16
Yes, I know the cause of problem and already had a correct search result by changing document mapping.

However, I believed that somewhere in mantle or PopCommerce there's problematic search and if somebody do searching on current documents with the same condition they will run into this problem.

Can we put some notes in Document definition as a warning about the usage?

Is it possible to do an enhancement that allow to use "nested" or not in document mapping?

**Comment by shendepu** [comment] 2017-04-12 02:21
There is one line comment in https://github.com/moqui/moqui-elasticsearch/blob/master/src/main/groovy/org/moqui/elasticsearch/ElasticSearchUtil.groovy#L140 which is the reason why not using nested datatypes by default

>  // NOTE: not doing type:'nested', ES docs say arrays should have it but they go into separate documents and term/facet searches fail!

**Comment by jonesde** [comment] 2017-04-12 03:45
That comment is the result of attempting this, partly for the reason of querying by fields associated in an object within the JSON document, but ran into issues. This does need to be revisited sooner or later, and there are significant changes in more recent versions of ElasticSearch that also change how these work a bit, so there might be a better solution possible now and ideally one that is backward compatible, but from looking before it would NOT be... in other words not just the OOTB searches/queries in mantle-usl and such would have to be changed but all custom code that does searches on field in arrays of objects (ie any type many relationship used in the DataDocument definition).

**Comment by jonesde** [comment] 2017-04-12 03:48
BTW, I don't have any plans to document this right now. It is actually the expected behavior if you understand how ElasticSearch handles such things, and there is significant documentation available for ElasticSearch. Part of the point of using third party open source libraries is to leverage not just their functionality but also their documentation. In other words, if you use features in Moqui that rely on third party libraries you should learn about those as well.

**Comment by locnguyenx** [comment] 2017-04-12 07:40
In deed, I have changed document mapping in ElasticSearchUtil.groovy to apply `nested` type to document (for all indexes), and successfully search by related fields using a nested query.
To not impact other search functionalities in mantle and add-ons, I'm considering a work-around which uses a new index (with a specific name/prefix) to apply nested type mapping.

**Comment by jonesde** [comment] 2017-05-12 16:27
In commit #9dc6e38 I changed the mappings to use type:nested and also include_in_root:true.

This combination appears to support both nested queries and query strings with full path field names (which is the main use case and necessary to support to not break current functionality).

One concern with this is that the include_in_root option (along with include_in_parent) doesn't seem to be documented any more and there are discussions are deprecating/removing it. We'll have to keep an eye on this and if things change in ElasticSearch (which they SO often have done in the last couple years) we may have to find another solution or simply remove using type:nested by default.

You still have to use a nested query to limit results by multiple fields in the same nested object, it doesn't look like the query string syntax supports anything like this, but at least now there is a possible solution with the default mappings. The ElasticSearch API would have to be used directly as the search#DataDocuments service only supports query string searches.

To make things more annoying for something like this there is no good way to do a query by JSON source through the Java API (removed in 5.0), unless something has changed for that.

On a side note, because we can't do queries by JSON source and because ElasticSearch over time has made it more difficult to run embedded (Moqui had to use some undocumented tricks to get this to work for ES versions 5+) I've considered changing ElasticSearch integration to run over the REST API instead of the Java API with an external instance, hopefully still run automatically with Moqui starts.

One disadvantage to that is that performance would drop as we no longer have an embedded ES node that can communicate with other ES nodes so there is an extra hop involved.

On the other hand this might be easier for larger deployments with a separate cluster of ElasticSearch servers. Right now that works fine by changing the configuration (in elasticsearch.yml) to have the embedded nodes run without any data persisted locally.

For now this makes nested queries possible so closing this issue. Some sort of OOTB service allowing nested queries is another issue.

**Closed by jonesde** 2017-05-12 16:27 UTC
Labels: enhancement
